linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - graph/generated

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0
