package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"

	"github.com/carldunham/nestmed/eval1/backend/graph/generated"
	"github.com/carldunham/nestmed/eval1/backend/graph/model"
)

// ProcessTranscript is the resolver for the processTranscript field.
func (r *mutationResolver) ProcessTranscript(ctx context.Context, transcript string) (*model.VisitSummary, error) {
	return r.Resolver.Query().AnalyzeTranscript(ctx, transcript)
}

// AnalyzeTranscript is the resolver for the analyzeTranscript field.
func (r *queryResolver) AnalyzeTranscript(ctx context.Context, transcript string) (*model.VisitSummary, error) {
	return r.Resolver.service.AnalyzeTranscript(ctx, transcript)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
